development:
  bucket: clickandbuy
  access_key_id: AKIAJHNEN7RZNC2VG3LA
  secret_access_key: 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

production:
  bucket: clickandbuy
  access_key_id: AKIAJHNEN7RZNC2VG3LA
  secret_access_key: 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